from typing import Optional

# -- simd_ops --

def pack_binary(codes: list[int]) -> list[int]:
    """Pack binary codes (0/1 bytes) into a bitfield."""
    ...

def unpack_binary(packed: list[int], dim: int) -> list[int]:
    """Unpack a bitfield back into one byte per bit (0 or 1)."""
    ...

def hamming_distance(a: list[int], b: list[int]) -> int:
    """Hamming distance between two packed bit-vectors."""
    ...

def asymmetric_inner_product(query: list[float], codes: list[int]) -> float:
    """Asymmetric inner product: f32 query vs packed 1-bit codes (bit=1 -> +1, bit=0 -> -1)."""
    ...

def asymmetric_l2_squared(query: list[float], codes: list[int]) -> float:
    """Asymmetric L2 distance squared: ||q - b||^2 where b in {-1,+1}^D."""
    ...

def multibit_inner_product(query: list[float], codes: list[int], total_bits: int) -> float:
    """Multi-bit inner product with centered codes."""
    ...

# -- rabitq --

class QuantizedVector:
    """Quantized vector produced by RaBitQ."""

    @property
    def dimension(self) -> int: ...
    @property
    def ex_bits(self) -> int: ...
    @property
    def delta(self) -> float: ...
    @property
    def vl(self) -> float: ...
    @property
    def f_add(self) -> float: ...
    @property
    def f_rescale(self) -> float: ...
    @property
    def f_error(self) -> float: ...
    @property
    def residual_norm(self) -> float: ...
    @property
    def binary_codes(self) -> list[int]: ...
    @property
    def extended_codes(self) -> list[int]: ...
    @property
    def codes(self) -> list[int]: ...

class RaBitQQuantizer:
    """RaBitQ quantizer with extended bit support."""

    def __init__(self, dimension: int, seed: int, total_bits: int = 4) -> None: ...
    def fit(self, vectors: list[float], num_vectors: int) -> None: ...
    def set_centroid(self, centroid: list[float]) -> None: ...
    def quantize(self, vector: list[float]) -> QuantizedVector: ...
    def approximate_l2_sqr(self, query: list[float], quantized: QuantizedVector) -> float: ...
    def approximate_distance(self, query: list[float], quantized: QuantizedVector) -> float: ...

# -- ternary --

class TernaryVector:
    """Ternary quantized vector ({-1, 0, +1} per dimension)."""

    @property
    def dimension(self) -> int: ...
    @property
    def original_norm(self) -> float: ...
    @property
    def sparsity(self) -> float: ...
    @property
    def memory_bytes(self) -> int: ...
    def get(self, idx: int) -> int: ...
    def to_list(self) -> list[int]: ...

class TernaryQuantizer:
    """Ternary quantizer: maps each dimension to {-1, 0, +1}."""

    def __init__(
        self,
        dimension: int,
        threshold_high: float = 0.3,
        threshold_low: float = -0.3,
        normalize: bool = True,
        target_sparsity: Optional[float] = None,
    ) -> None: ...
    def fit(self, vectors: list[float], num_vectors: int) -> None: ...
    def quantize(self, vector: list[float]) -> TernaryVector: ...

def ternary_inner_product(a: TernaryVector, b: TernaryVector) -> int:
    """Inner product between two ternary vectors."""
    ...

def ternary_cosine_similarity(a: TernaryVector, b: TernaryVector) -> float:
    """Cosine similarity between two ternary vectors."""
    ...

def ternary_asymmetric_inner_product(query: list[float], quantized: TernaryVector) -> float:
    """Asymmetric inner product: f32 query vs ternary codes."""
    ...

def ternary_asymmetric_cosine_distance(query: list[float], quantized: TernaryVector) -> float:
    """Asymmetric cosine distance: 1 - cos(query, quantized)."""
    ...

def ternary_hamming(a: TernaryVector, b: TernaryVector) -> Optional[int]:
    """Hamming distance between two ternary vectors. Returns None if dimensions differ."""
    ...
